# Importando biblioteca

In [53]:
import pandas as pd

In [6]:
dados = np.random.randn(2, 3)

In [7]:
dados

array([[-0.23847145,  1.52471327,  1.62099585],
       [-0.66742625, -0.86705188,  1.63625326]])

In [8]:
dados * 10

array([[-2.38471446, 15.24713269, 16.20995854],
       [-6.67426254, -8.67051884, 16.36253256]])

In [9]:
dados + dados

array([[-0.47694289,  3.04942654,  3.24199171],
       [-1.33485251, -1.73410377,  3.27250651]])

In [10]:
dados.shape

(2, 3)

In [11]:
dados.dtype

dtype('float64')

# Conversão de dados

In [13]:
dados1 = [6, 7.5, 8, 0, 1]

In [14]:
matriz1 = np.array(dados1)

In [15]:
matriz1

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
dados2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [17]:
matriz2 = np.array(dados2)

In [18]:
matriz2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
matriz2.shape

(2, 4)

In [21]:
matriz2.ndim

2

In [22]:
matriz1.dtype

dtype('float64')

In [23]:
matriz2.dtype

dtype('int32')

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [27]:
np.empty((2, 3, 2))

array([[[1.04510310e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.12465777e-312, 6.82116729e-043]],

       [[7.43099726e-091, 7.12309085e-067],
        [2.81299236e-033, 1.39641553e-075],
        [3.99910963e+252, 9.51330831e-047]]])

In [28]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Tipos de dados

In [30]:
matriz1 = np.array([1, 2, 3], dtype=np.float64)

In [31]:
matriz2 = np.array([1, 2, 3], dtype=np.int32)

In [32]:
matriz1.dtype

dtype('float64')

In [34]:
matriz2.dtype

dtype('int32')

In [35]:
matriz = np.array([1, 2, 3, 4, 5])

In [36]:
matriz.dtype

dtype('int32')

In [37]:
float_matriz = matriz.astype(np.float64)

In [40]:
float_matriz.dtype

dtype('float64')

In [41]:
matriz = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [42]:
matriz

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [43]:
matriz.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

# Strings Numéricas

In [45]:
strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [46]:
strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [47]:
int = np.arange(10)

In [49]:
calibre = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

* Conversão

In [50]:
int.astype(calibre.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [51]:
vazio_uint32 = np.empty(8, dtype = 'u4')

In [52]:
vazio_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)