Carregando bibliotecas

In [21]:
import numpy as np
np.random.seed(0)


Criando um array com os números da megasena do Concurso 2.644 • Sábado 14/10/2023

In [77]:
megasena1 = np.array([4,17,22,28,30,49])
megasena1

array([ 4, 17, 22, 28, 30, 49])

Apresentando todos os números participantes em sorteio

In [80]:
megasena = np.arange(1, 61, 1)
megasena


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

Fazendo um sorteio com apenas uma dimensão

In [79]:
megasena1 =  np.random.randint(60, size=6)
print("quantidades de dimensões:", megasena.ndim)

quantidades de dimensões: 1


In [78]:
megasena1

array([ 4, 17, 22, 28, 30, 49])

Especificações

In [81]:
print("quantidade de dimensões: ", megasena1.ndim)
print("forma:", megasena1.shape)
print("tamanho: ", megasena1.size)

quantidade de dimensões:  1
forma: (6,)
tamanho:  6


Supondo que eu queira sortear apenas o primeiro número e o último do sorteio

In [84]:
megasena1 = np.array([4,17,22,28,30,49])
megasena1

array([ 4, 17, 22, 28, 30, 49])

In [88]:
megasena1[0]

4

In [90]:
megasena1[5]

49

Fazendo dois sorteios multi-dimensionais

In [102]:
megasena2 = np.random.randint(60, size=(2, 6))
print("quantidade de dimensões: ", megasena2.ndim)


quantidade de dimensões:  2


In [103]:
megasena2

array([[58,  4, 17,  5, 30, 24],
       [ 3,  5, 40, 36, 58, 49]])

Pegando os dois primeiros números do sorteios

In [98]:
megasena2[0,0]

31

In [99]:
megasena2[1,0]

35

In [101]:
#Modificando o primeiro número do primeiro sorteio
megasena2[0,0] = 17
megasena2

array([[17, 20,  6,  9, 27, 47],
       [35, 19, 12, 18, 49, 10],
       [34, 33, 43,  3, 12, 36]])

Especificações

In [67]:
print("quantidade de dimensões: ", megasena2.ndim)
print("forma:", megasena2.shape)
print("tamanho: ", megasena2.size)

quantidade de dimensões:  2
forma: (3, 6)
tamanho:  18


Fazendo sorteios para 2 meses de sorteios, supondo que haja 2 sorteios cada semana do mês

In [63]:
megasena3 = np.random.randint(60, size=(2, 8, 6))

In [64]:
megasena3

array([[[50, 28, 14, 37, 27, 54],
        [36, 31, 29, 50, 46, 29],
        [50, 33, 12, 32, 41, 16],
        [ 2,  8, 51, 10, 48, 26],
        [27, 56, 56,  1,  0,  5],
        [24, 34, 15,  3, 46, 37],
        [43, 19, 24,  6, 20,  6],
        [28, 51,  6,  2, 28, 28]],

       [[38, 37, 59,  5, 45,  9],
        [36, 54, 13, 21, 59, 31],
        [17, 35, 45, 51, 58,  8],
        [25, 21, 45, 37, 22, 16],
        [25, 46, 55, 37,  1,  5],
        [ 6, 12, 26, 10, 59, 54],
        [14,  8,  7, 45,  5, 47],
        [59, 42,  3, 10, 50, 57]]])

In [68]:
print("quantidade de dimensões: ", megasena3.ndim)
print("forma:", megasena3.shape)
print("tamanho: ", megasena3.size)

quantidade de dimensões:  3
forma: (2, 8, 6)
tamanho:  96
