Carregando bibliotecas

In [46]:
import numpy as np
np.random.seed(0)


Criando um array com os números da megasena do Concurso 2.644 • Sábado 14/10/2023

In [47]:
megasena_sorteio = np.array([4,17,22,28,30,49])
megasena_sorteio

array([ 4, 17, 22, 28, 30, 49])

Apresentando todos os números participantes em sorteio

In [48]:
megasena = np.arange(1, 61, 1)
megasena


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

Fazendo um sorteio com apenas uma dimensão

In [49]:
megasena1 = np.random.randint(1, 61, size= 6)
print("quantidades de dimensões:", megasena.ndim)

quantidades de dimensões: 1


In [50]:
megasena1

array([45, 48, 54,  1,  4, 60])

Especificações

In [51]:
print("quantidade de dimensões: ", megasena1.ndim)
print("forma:", megasena1.shape)
print("tamanho: ", megasena1.size)

quantidade de dimensões:  1
forma: (6,)
tamanho:  6


Supondo que eu queira sortear apenas o primeiro número e o último do sorteio

In [52]:
megasena1 = np.array([4,17,22,28,30,49])
megasena1

array([ 4, 17, 22, 28, 30, 49])

In [53]:
megasena1[0]

4

In [54]:
megasena1[5]

49

Fazendo dois sorteios multi-dimensionais

In [55]:
megasena3 = np.random.randint(1, 61, size=(2, 6))
print("quantidade de dimensões: ", megasena2.ndim)


quantidade de dimensões:  2


In [56]:
megasena2

array([[18, 39,  9, 19, 21, 50],
       [36, 23,  6, 24, 24, 12]])

Pegando os dois primeiros números do sorteios

In [58]:
megasena2[0,0]

18

In [59]:
megasena2[1,0]

36

In [62]:
#Modificando o primeiro número do primeiro sorteio
megasena2[0,0] = 19
megasena2

array([[19, 39,  9, 19, 21, 50],
       [36, 23,  6, 24, 24, 12]])

Especificações

In [63]:
print("quantidade de dimensões: ", megasena2.ndim)
print("forma:", megasena2.shape)
print("tamanho: ", megasena2.size)

quantidade de dimensões:  2
forma: (2, 6)
tamanho:  12


Fazendo sorteios para 2 meses, supondo que haja 2 sorteios cada semana do mês

In [64]:
megasena3 = np.random.randint(1, 61, size=(2, 8, 6))

In [65]:
megasena3

array([[[59,  2, 39, 40, 24, 47],
        [25, 18, 38, 26, 14,  9],
        [10, 21, 52, 17, 52,  6],
        [16, 48,  1, 19, 36, 25],
        [50, 52, 30, 20, 20, 15],
        [40, 33,  2, 10, 58, 33],
        [32, 11, 53, 24, 36, 12],
        [51, 56, 29, 35,  1,  1]],

       [[37, 54,  6, 39, 41, 53],
        [18, 16,  5, 42, 43, 59],
        [32, 57,  2,  2, 40, 42],
        [58, 36, 39, 56, 12, 47],
        [19, 28,  1, 15, 36, 54],
        [13, 58, 43, 21, 12,  5],
        [ 7,  5, 48, 53,  4, 13],
        [37, 53, 41, 15, 16, 21]]])

In [66]:
print("quantidade de dimensões: ", megasena3.ndim)
print("forma:", megasena3.shape)
print("tamanho: ", megasena3.size)

quantidade de dimensões:  3
forma: (2, 8, 6)
tamanho:  96
