Carregando bibliotecas

In [23]:
import numpy as np

Criando uma matriz com os números da megasena do Concurso 2.644 • Sábado 14/10/2023

In [24]:
megasena_sorteio = np.array([4,17,22,28,30,49])
megasena_sorteio

array([ 4, 17, 22, 28, 30, 49])

Apresentando todos os números participantes em sorteio

In [25]:
megasena_num = np.arange(1, 61, 1)
megasena_num


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

Fazendo um sorteio com apenas uma dimensão

In [26]:
megasena1 = np.random.choice(megasena_num, size=6, replace=False)


In [27]:
print("Números da Mega Sena:", megasena1)


Números da Mega Sena: [ 5  8 59 42 44 32]


In [28]:
print("quantidades de dimensões:", megasena1.ndim)

quantidades de dimensões: 1


Especificações

In [29]:
print("quantidade de dimensões: ", megasena1.ndim)
print("forma:", megasena1.shape)
print("tamanho: ", megasena1.size)

quantidade de dimensões:  1
forma: (6,)
tamanho:  6


Supondo que eu queira sortear apenas o primeiro número e o último do sorteio

In [30]:
megasena_sorteio

array([ 4, 17, 22, 28, 30, 49])

In [31]:
megasena_sorteio[0]

4

In [32]:
megasena_sorteio[5]

49

Fazendo dois sorteios multi-dimensionais

In [33]:
megasena2 = np.random.choice(megasena_num, size=(2, 6), replace=False)

In [34]:
megasena2

array([[30, 46, 24, 48,  9, 31],
       [27, 21, 60, 26, 23, 18]])

In [35]:
print("quantidade de dimensões: ", megasena2.ndim)

quantidade de dimensões:  2


Pegando os dois primeiros números do sorteios

In [36]:
megasena2[0,0]

30

In [37]:
megasena2[1,0]

27

In [38]:
#Modificando o primeiro número do primeiro sorteio
megasena2[0,0] = 19
megasena2

array([[19, 46, 24, 48,  9, 31],
       [27, 21, 60, 26, 23, 18]])

Especificações

In [39]:
print("quantidade de dimensões: ", megasena2.ndim)
print("forma:", megasena2.shape)
print("tamanho: ", megasena2.size)

quantidade de dimensões:  2
forma: (2, 6)
tamanho:  12


Fazendo sorteios para 2 meses, supondo que haja um sorteio cada semana do mês, com três dimensões

In [40]:
megasena3 = np.random.choice(megasena_num, size=(2, 4, 6), replace=False)

In [41]:
megasena3

array([[[31, 46,  7, 27, 44, 56],
        [32,  3, 58, 29,  4, 51],
        [17, 25, 35, 59, 54,  2],
        [55,  8, 22, 34, 36, 41]],

       [[20, 12, 43, 45, 10, 50],
        [24, 30, 15, 13, 28, 60],
        [52, 11, 49, 47, 57, 33],
        [18, 53, 40, 48, 14, 38]]])

In [42]:
print("quantidade de dimensões: ", megasena3.ndim)
print("forma:", megasena3.shape)
print("tamanho: ", megasena3.size)

quantidade de dimensões:  3
forma: (2, 4, 6)
tamanho:  48
